language: php

php:
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer install --prefer-source --dev
  
script:
  - phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover